# Setup
title:        Random Studios
tagline:      A place for our random projects
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Random Studios
  url:        https://randomstudios.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
